###
POST http://localhost:8080/person
Content-Type: application/json

{
  "firstname":"Ivanov",
  "surname":"Ivan",
  "lastname":"Ivanovich",
  "birthday":"1999-06-07"
}

###
GET http://localhost:8080/person
Content-Type: application/json

###
PUT http://localhost:8080/person/1
Content-Type: application/json

{
"firstname":"Ivanovsssssssss",
"surname":"Ivan",
"lastname":"Ivanovich",
"birthday":"1999-06-07"
}

###
DELETE http://localhost:8080/person/4
Content-Type: application/json
